source/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', include('django_social_share.urls')),
    path('', include("webapp.urls")),
    path('accounts/', include("accounts.urls")),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webapp/urls.py
from django.urls import path

from webapp.views.album import UpdateAlbum, DeleteAlbum, OneAlbumView, CreateAlbum
from webapp.views.photos import IndexView, CreatePhoto, UpdatePhoto, PhotoView, DeletePhoto, FavView

app_name = 'webapp'

urlpatterns = [
    path('', IndexView.as_view(), name="index"),
    path('photo/add/', CreatePhoto.as_view(), name="add"),
    path('photo/<int:pk>/update/', UpdatePhoto.as_view(), name="update"),
    path('photo/<int:pk>/', PhotoView.as_view(), name="photo_view"),
    path('photo/<int:pk>/delete/', DeletePhoto.as_view(), name="delete"),
    path('album/<int:pk>/update/', UpdateAlbum.as_view(), name="update_album"),
    path('album/<int:pk>/delete/', DeleteAlbum.as_view(), name="delete_album"),
    path('album/add/', CreateAlbum.as_view(), name="add_album"),
    path('album/<int:pk>/', OneAlbumView.as_view(), name="one_album"),
    path('fav/<int:pk>/', FavView.as_view(), name='fav'),

]

webapp/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse


# Create your models here.

class Photo(models.Model):
    image = models.ImageField(upload_to='images', blank=False, null=False, verbose_name='image')
    description = models.TextField(null=False, blank=False, verbose_name='description')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="date of creation")
    user = models.ManyToManyField(get_user_model(), verbose_name='User', related_name='photos')
    album = models.ForeignKey('webapp.Album', on_delete=models.CASCADE, blank=True, related_name='photos',
                              verbose_name='photos')
    public = models.BooleanField(default=True)
    fav = models.ManyToManyField(get_user_model(), related_name='fav', blank=True)

    def __str__(self):
        return f"{self.id}. {self.description}: {self.user}"

    def get_absolute_url(self):
        return reverse("webapp:photo_view", kwargs={"pk": self.pk})

    def total_favs(self):
        return self.fav.count()

    class Meta:
        db_table = "photos"
        verbose_name = "photos"
        verbose_name_plural = "Photos"


class Album(models.Model):
    created_at = models.DateField(blank=True, verbose_name="date of creation")
    name = models.CharField(max_length=50, null=False, blank=False, verbose_name='album name')
    description = models.TextField(null=True, blank=True, verbose_name='album description')
    user = models.ManyToManyField(get_user_model(), verbose_name='User', related_name='albums')
    public = models.BooleanField(default=1)

    def __str__(self):
        return f"{self.name}"

    # class Meta:
    #     db_table = "albums"
    #     verbose_name = "albums"
    #     verbose_name_plural = "albums"

webapp/forms.py
from django import forms
from django.forms import widgets

from webapp.models import Photo, Album


class PhotoForm(forms.ModelForm):
    class Meta:
        model = Photo
        fields = ['image', 'description', 'album', 'public']
        # widgets = {
        #     'album': widgets.RadioSelect
        # }


class AlbumForm(forms.ModelForm):
    class Meta:
        model = Album
        exclude = ['user']
        widgets = {
            'created_at': widgets.SelectDateWidget,
        }


class AlbumFormUser(forms.ModelForm):
    class Meta:
        model = Album
        exclude = ['user']


class UserForm(forms.ModelForm):
    class Meta:
        model = Album
        fields = ['user']
        widgets = {'user': widgets.CheckboxSelectMultiple}

webapp/views/album.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from webapp.forms import AlbumForm
from webapp.models import Album


# class AllAlbumsView(ListView):
#     template_name = 'albums/albums.html'
#     context_object_name = 'albums'
#
#     def get_queryset(self):
#         return Album.objects.all().order_by('-created_at')


class OneAlbumView(LoginRequiredMixin, DetailView):
    template_name = "albums/one_album.html"
    model = Album

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['photos'] = self.object.photos.order_by("-created_at")
        return context


class CreateAlbum(LoginRequiredMixin, CreateView):
    form_class = AlbumForm
    template_name = "albums/new.html"

    def get_success_url(self):
        return reverse('webapp:one_album', kwargs={"pk": self.object.pk})

    def form_valid(self, form):
        project = form.save()
        user_id = self.request.user
        project.user.add(user_id)
        project.save()
        return super().form_valid(form)


class UpdateAlbum(PermissionRequiredMixin, UpdateView):
    model = Album
    template_name = 'albums/update.html'
    form_class = AlbumForm
    context_object_name = 'album'
    permission_required = 'webapp.change_album'

    def get_success_url(self):
        return reverse('webapp:album_list')


class DeleteAlbum(PermissionRequiredMixin, DeleteView):
    model = Album
    context_object_name = 'album'
    template_name = 'albums/delete.html'
    success_url = reverse_lazy('webapp:index')
    permission_required = 'webapp.delete_album'

webapp/views/photos.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views import View
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from webapp.forms import PhotoForm
from webapp.models import Photo


# Create your views here.

class FavView(LoginRequiredMixin, View):
    def get(self, request, *args, pk, **kwargs):
        photo = Photo.objects.get(pk=pk)
        user = self.request.user
        if user in photo.fav.all():
            photo.fav.remove(user)
        else:
            photo.fav.add(user)
        return JsonResponse ({'count': photo.fav.count()})




class IndexView(ListView):  # пермишны на забудь
    template_name = 'photos/index.html'
    context_object_name = 'photos'

    def get_queryset(self):
        return Photo.objects.all().order_by('created_at')


class PhotoView(LoginRequiredMixin, DetailView):  # пермишны на забудь
    template_name = "photos/photo.html"
    model = Photo
    context_object_name = 'photo_obj'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class CreatePhoto(LoginRequiredMixin, CreateView):  # пермишны на забудь
    form_class = PhotoForm
    template_name = "photos/create.html"

    def get_success_url(self):
        return reverse('webapp:index')


class UpdatePhoto(PermissionRequiredMixin, UpdateView):  # пермишны на забудь
    model = Photo
    template_name = 'photos/update.html'
    form_class = PhotoForm
    context_object_name = 'photo'
    permission_required = 'webapp.change_photo'

    def get_success_url(self):
        return reverse('webapp:photo_view', kwargs={'pk': self.object.pk})


class DeletePhoto(PermissionRequiredMixin, DeleteView):  # пермишны на забудь
    model = Photo
    context_object_name = 'photo'
    template_name = 'photos/delete.html'
    success_url = reverse_lazy('webapp:index')
    permission_required = 'webapp.delete_photo'

webapp/templates/albums/albums.html
{% extends 'base.html' %}
{% load static %}
{% block nav %}
{% endblock %}
{% block content %}
    <div class="mt-4 mb-4">
        <h1 style="text-align: center">Альбомы</h1>
    </div>
    <div class="row">
        {% for album in albums %}
            <div class="col-12 col-md-6 col-lg-6">
                <div class="card">
                    <div class="card-body mt-2 mb-2">
                        <h5 class="card-title">{{ album.name }}</h5>
                        <p class="card-text">{{ album.description }}</p>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

webapp/templates/albums/delete.html
{%  extends 'base.html' %}
{% block content %}
    <p>Do you want to delete {{ album.name }}?</p>
    <form action="" method="POST">
    {%  csrf_token %}
        <input name="Yes" type="submit" value="Yes"/>
        <input name="No" type="submit" value="No"/>
    </form>
{%  endblock %}

webapp/templates/albums/new.html
{% extends "base.html" %}
{% block title %}Создание альбома{% endblock %}
{% block content %}
    <h1>Create album</h1>
    <form action="" method="post">
        {% include "partial/form.html" with button_text="Create" %}
    </form>
{% endblock %}

webapp/templates/albums/one_album.html
{% extends "base.html" %}
{% block nav %}
    <li class="menu-right">
        <a href="{% url 'webapp:add' %}"
           class="nav-link mt-2">New photo</a>
    </li>
{% endblock %}
{% block content %}
    <div class="row mt-4">
        {% for album in albums %}
            <p class="card-text"><b>Name:</b> {{ album.name }}</p>
            <p class="card-text"><b>Description:</b> {{ album.description }}</p>
        {% endfor %}
        <a href="{% url 'webapp:update_album' album.pk %}"
           class="nav-link">Update album</a>
        <a href="{% url 'webapp:delete_album' album.pk %}"
           class="nav-link">Delete album</a>
        {% for photo in photos %}
            <div class="col-12 col-md-6 col-lg-6">
                <div class="card">
                    <div class="card-body">
                        <img src="{{ photo.image.url }}"
                             class="card-img-top w-25"
                             alt="...">
                        <h5 class="card-title">{{ photo.name }}</h5>
                        <p class="card-text">{{ photo.description }}</p>
                        <p class="card-text">{{ photo.user }}</p>
                        <a href="{% url 'webapp:update' photo.pk %}"
                           title="update photo">
                            <svg xmlns="http://www.w3.org/2000/svg"
                                 width="16"
                                 height="16"
                                 fill="currentColor"
                                 class="bi bi-pencil-square"
                                 viewBox="0 0 16 16">
                                <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"></path>
                                <path fill-rule="evenodd"
                                      d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"></path>
                            </svg>
                        </a>
                        <a href="{% url 'webapp:delete' photo.pk %}"
                           title="delete task">
                            <svg xmlns="http://www.w3.org/2000/svg"
                                 width="16"
                                 height="16"
                                 fill="currentColor"
                                 class="bi bi-x-circle-fill"
                                 viewBox="0 0 16 16">
                                <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM5.354 4.646a.5.5 0 1 0-.708.708L7.293 8l-2.647 2.646a.5.5 0 0 0 .708.708L8 8.707l2.646 2.647a.5.5 0 0 0 .708-.708L8.707 8l2.647-2.646a.5.5 0 0 0-.708-.708L8 7.293 5.354 4.646z"></path>
                            </svg>
                        </a>
                        <a href="{% url 'webapp:photo_view' photo.pk %}"
                           title="view task">
                            <svg xmlns="http://www.w3.org/2000/svg"
                                 width="16"
                                 height="16"
                                 fill="currentColor"
                                 class="bi bi-info-circle-fill"
                                 viewBox="0 0 16 16">
                                <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z"></path>
                            </svg>
                        </a>

                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

webapp/templates/albums/update.html
{% extends 'base.html' %}
{% block content %}
<h1 >Обновить альбом</h1>
<form action="" method="post">
    {% include "partial/form.html" with button_text="Update" %}
</form>
<br/>
<a href="{% url 'webapp:index' %}">Main page</a>

{% endblock %}