source/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', include('django_social_share.urls')),
    path('', include("webapp.urls")),
    path('accounts/', include("accounts.urls")),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webapp/urls.py
from django.urls import path

from webapp.views.album import UpdateAlbum, DeleteAlbum, OneAlbumView, CreateAlbum
from webapp.views.photos import IndexView, CreatePhoto, UpdatePhoto, PhotoView, DeletePhoto, FavView

app_name = 'webapp'

urlpatterns = [
    path('', IndexView.as_view(), name="index"),
    path('photo/add/', CreatePhoto.as_view(), name="add"),
    path('photo/<int:pk>/update/', UpdatePhoto.as_view(), name="update"),
    path('photo/<int:pk>/', PhotoView.as_view(), name="photo_view"),
    path('photo/<int:pk>/delete/', DeletePhoto.as_view(), name="delete"),
    path('album/<int:pk>/update/', UpdateAlbum.as_view(), name="update_album"),
    path('album/<int:pk>/delete/', DeleteAlbum.as_view(), name="delete_album"),
    path('album/add/', CreateAlbum.as_view(), name="add_album"),
    path('album/<int:pk>/', OneAlbumView.as_view(), name="one_album"),
    path('fav/<int:pk>/', FavView.as_view(), name='fav'),

]

webapp/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse


# Create your models here.

class Photo(models.Model):
    image = models.ImageField(upload_to='images', blank=False, null=False, verbose_name='image')
    description = models.TextField(null=False, blank=False, verbose_name='description')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="date of creation")
    user = models.ManyToManyField(get_user_model(), verbose_name='User', related_name='photos')
    album = models.ForeignKey('webapp.Album', on_delete=models.CASCADE, blank=True, related_name='photos',
                              verbose_name='photos')
    public = models.BooleanField(default=True)
    fav = models.ManyToManyField(get_user_model(), related_name='fav', blank=True)

    def __str__(self):
        return f"{self.id}. {self.description}: {self.user}"

    def get_absolute_url(self):
        return reverse("webapp:photo_view", kwargs={"pk": self.pk})

    def total_favs(self):
        return self.fav.count()

    class Meta:
        db_table = "photos"
        verbose_name = "photos"
        verbose_name_plural = "Photos"


class Album(models.Model):
    created_at = models.DateField(blank=True, verbose_name="date of creation")
    name = models.CharField(max_length=50, null=False, blank=False, verbose_name='album name')
    description = models.TextField(null=True, blank=True, verbose_name='album description')
    user = models.ManyToManyField(get_user_model(), verbose_name='User', related_name='albums')
    public = models.BooleanField(default=1)

    def __str__(self):
        return f"{self.name}"

    # class Meta:
    #     db_table = "albums"
    #     verbose_name = "albums"
    #     verbose_name_plural = "albums"

webapp/forms.py
from django import forms
from django.forms import widgets

from webapp.models import Photo, Album


class PhotoForm(forms.ModelForm):
    class Meta:
        model = Photo
        fields = ['image', 'description', 'album', 'public']
        # widgets = {
        #     'album': widgets.RadioSelect
        # }


class AlbumForm(forms.ModelForm):
    class Meta:
        model = Album
        exclude = ['user']
        widgets = {
            'created_at': widgets.SelectDateWidget,
        }


class AlbumFormUser(forms.ModelForm):
    class Meta:
        model = Album
        exclude = ['user']


class UserForm(forms.ModelForm):
    class Meta:
        model = Album
        fields = ['user']
        widgets = {'user': widgets.CheckboxSelectMultiple}

webapp/views/album.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from webapp.forms import AlbumForm
from webapp.models import Album


# class AllAlbumsView(ListView):
#     template_name = 'albums/albums.html'
#     context_object_name = 'albums'
#
#     def get_queryset(self):
#         return Album.objects.all().order_by('-created_at')


class OneAlbumView(LoginRequiredMixin, DetailView):
    template_name = "albums/one_album.html"
    model = Album

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['photos'] = self.object.photos.order_by("-created_at")
        return context


class CreateAlbum(LoginRequiredMixin, CreateView):
    form_class = AlbumForm
    template_name = "albums/new.html"

    def get_success_url(self):
        return reverse('webapp:one_album', kwargs={"pk": self.object.pk})

    def form_valid(self, form):
        project = form.save()
        user_id = self.request.user
        project.user.add(user_id)
        project.save()
        return super().form_valid(form)


class UpdateAlbum(PermissionRequiredMixin, UpdateView):
    model = Album
    template_name = 'albums/update.html'
    form_class = AlbumForm
    context_object_name = 'album'
    permission_required = 'webapp.change_album'

    def get_success_url(self):
        return reverse('webapp:album_list')


class DeleteAlbum(PermissionRequiredMixin, DeleteView):
    model = Album
    context_object_name = 'album'
    template_name = 'albums/delete.html'
    success_url = reverse_lazy('webapp:index')
    permission_required = 'webapp.delete_album'

webapp/views/photos.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views import View
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from webapp.forms import PhotoForm
from webapp.models import Photo


# Create your views here.

class FavView(LoginRequiredMixin, View):
    def get(self, request, *args, pk, **kwargs):
        photo = Photo.objects.get(pk=pk)
        user = self.request.user
        if user in photo.fav.all():
            photo.fav.remove(user)
        else:
            photo.fav.add(user)
        return JsonResponse ({'count': photo.fav.count()})




class IndexView(ListView):  # пермишны на забудь
    template_name = 'photos/index.html'
    context_object_name = 'photos'

    def get_queryset(self):
        return Photo.objects.all().order_by('created_at')


class PhotoView(LoginRequiredMixin, DetailView):  # пермишны на забудь
    template_name = "photos/photo.html"
    model = Photo
    context_object_name = 'photo_obj'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class CreatePhoto(LoginRequiredMixin, CreateView):  # пермишны на забудь
    form_class = PhotoForm
    template_name = "photos/create.html"

    def get_success_url(self):
        return reverse('webapp:index')


class UpdatePhoto(PermissionRequiredMixin, UpdateView):  # пермишны на забудь
    model = Photo
    template_name = 'photos/update.html'
    form_class = PhotoForm
    context_object_name = 'photo'
    permission_required = 'webapp.change_photo'

    def get_success_url(self):
        return reverse('webapp:photo_view', kwargs={'pk': self.object.pk})


class DeletePhoto(PermissionRequiredMixin, DeleteView):  # пермишны на забудь
    model = Photo
    context_object_name = 'photo'
    template_name = 'photos/delete.html'
    success_url = reverse_lazy('webapp:index')
    permission_required = 'webapp.delete_photo'

webapp/templates/photos/create.html
{% extends "base.html" %}
{% block title %}Adding new photo{% endblock %}
{% block content %}
    <h1>Add photo</h1>
    <form action="" method="post" enctype="multipart/form-data">
        {% include "partial/form.html" with button_text="Add" %}
    </form>
{% endblock %}

webapp/templates/photos/delete.html
{%  extends 'base.html' %}
{% block content %}
    <p>Do you want to delete {{ photo.description }}?</p>
    <form action="" method="POST" enctype="multipart/form-data">
    {%  csrf_token %}
        <input name="Yes" type="submit" value="Yes"/>
        <input name="No" type="submit" value="No"/>
    </form>
{%  endblock %}

webapp/templates/photos/index.html
{% extends 'base.html' %}
{% load social_share %}
{% load static %}

{% block nav %}
    {% if perms.webapp.add_photo or perms.webapp.add_album or user == photos.user %}
        <li class="menu-right mt-2">
            <a href="{% url 'webapp:add' %}"
               class="nav-link">Add new photo</a>
        </li>
        <li class="menu-right mt-2">
            <a href="{% url 'webapp:add_album' %}"
               class="nav-link">Add new album</a>
        </li>
    {% endif %}
{% endblock %}
{% block content %}
    <h1 style="text-align: center">Фотографии</h1>
    <div class="row">
        {% for photo in photos %}
            <div class="col-12 col-md-6 col-lg-6">
                <div class="card">
                    <div class="card-body">
                        <img src="{{ photo.image.url }}"
                             class="card-img-top w-25"
                             alt="...">
                        <p class="card-text"><b>Описание фотографии:</b> {{ photo.description }}</p>
                        <p class="card-text"><b>Дата создания</b>: {{ photo.created_at }}</p>
                        {% if user.is_authenticated or user == photos.user %}
                            <span id="photo-{{ photo.id }}">В избранных: {{ photo.fav.count }}</span>
                            <p><a data-photo-id="photo-{{ photo.id }}"
                                  class="favs"
                                  href="{% url "webapp:fav" photo.pk %}">
                                {% if request.user in photo.fav.all %} Удалить из избранного {% else %} Положить в
                                    избранное {% endif %}</a></p>
                            {% post_to_facebook object_or_url "Post to Facebook!" %}
                            {% post_to_twitter object_or_url "Post to Twitter!" %}
                            {% post_to_whatsapp object_or_url "Post to WhatsApp!" %}
                        {% endif %}
                        {% if perm.webapp.change_photo or perm.webapp.delete_photo %}
                            <a class="btn btn-dark"
                               href="{% url 'webapp:update' photo.pk %}">Update</a>
                            <a class="btn btn-dark"
                               href="{% url 'webapp:delete' photo.pk %}">Delete</a>
                            <a href="{{ photo.get_absolute_url }}"
                               class="card-link btn btn-dark">Подробнее</a>
                        {% endif %}
                        <a class="btn btn-dark"
                           href="{% url 'webapp:one_album' photo.album.pk %}">Album</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

webapp/templates/photos/photo.html
{% extends "base.html" %}
{% block nav %}
{% endblock %}
{% block content %}
    <p>Кто изображен на фото: {{ photo_obj.description }}</p>
    <img
            src="{{ photo_obj.image.url }}"
            class="card-img-top w-25"
            alt="..."
    >
    <div class="row mt-3 pb-4">
        {% for album in albums %}
            <div class="">
            <div class="card mb-3">
                <div class="card-body">
                    p class="card-text">Альбом: <a href="{% url 'webapp:one_album' album.pk %}"></a></p>
                </div>
                <div class="btn-group w-100"
                     role="group"
                     aria-label="Basic mixed styles example">
                </div>
            </div>
        {% empty %}
            <p>This photo does not have albums</p>
        {% endfor %}
        </div>
    </div>
{% endblock %}

webapp/templates/photos/update.html
{% extends 'base.html' %}
{% block content %}
<h1 >Update photo</h1>
<form action="" method="post" enctype="multipart/form-data">
    {% include "partial/form.html" with button_text="Update" %}
</form>
<br/>
<a href="{% url 'webapp:index' %}">Main page</a>
{% endblock %}