accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include

from accounts.views import RegisterView, UserDetailView, ChangeProfileView, ChangePasswordView

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('registration/', RegisterView.as_view(), name='registration'),
    path('<int:pk>/', UserDetailView.as_view(), name='profile'),
    # path('users/', UsersView.as_view(), name='UsersView'),
    # path('change/', ChangeProfileView.as_view(), name='change_profile'),
    # path('change/password/', ChangePasswordView.as_view(), name='change_password'),


]

source/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', include('django_social_share.urls')),
    path('', include("webapp.urls")),
    path('accounts/', include("accounts.urls")),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webapp/urls.py
from django.urls import path

from webapp.views.album import UpdateAlbum, DeleteAlbum, OneAlbumView, CreateAlbum
from webapp.views.photos import IndexView, CreatePhoto, UpdatePhoto, PhotoView, DeletePhoto, FavView

app_name = 'webapp'

urlpatterns = [
    path('', IndexView.as_view(), name="index"),
    path('photo/add/', CreatePhoto.as_view(), name="add"),
    path('photo/<int:pk>/update/', UpdatePhoto.as_view(), name="update"),
    path('photo/<int:pk>/', PhotoView.as_view(), name="photo_view"),
    path('photo/<int:pk>/delete/', DeletePhoto.as_view(), name="delete"),
    path('album/<int:pk>/update/', UpdateAlbum.as_view(), name="update_album"),
    path('album/<int:pk>/delete/', DeleteAlbum.as_view(), name="delete_album"),
    path('album/add/', CreateAlbum.as_view(), name="add_album"),
    path('album/<int:pk>/', OneAlbumView.as_view(), name="one_album"),
    path('fav/<int:pk>/', FavView.as_view(), name='fav'),

]

webapp/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse


# Create your models here.

class Photo(models.Model):
    image = models.ImageField(upload_to='images', blank=False, null=False, verbose_name='image')
    description = models.TextField(null=False, blank=False, verbose_name='description')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="date of creation")
    user = models.ManyToManyField(get_user_model(), verbose_name='User', related_name='photos')
    album = models.ForeignKey('webapp.Album', on_delete=models.CASCADE, blank=True, related_name='photos',
                              verbose_name='photos')
    public = models.BooleanField(default=True)
    fav = models.ManyToManyField(get_user_model(), related_name='fav', blank=True)

    def __str__(self):
        return f"{self.id}. {self.description}: {self.user}"

    def get_absolute_url(self):
        return reverse("webapp:photo_view", kwargs={"pk": self.pk})

    def total_favs(self):
        return self.fav.count()

    class Meta:
        db_table = "photos"
        verbose_name = "photos"
        verbose_name_plural = "Photos"


class Album(models.Model):
    created_at = models.DateField(blank=True, verbose_name="date of creation")
    name = models.CharField(max_length=50, null=False, blank=False, verbose_name='album name')
    description = models.TextField(null=True, blank=True, verbose_name='album description')
    user = models.ManyToManyField(get_user_model(), verbose_name='User', related_name='albums')
    public = models.BooleanField(default=1)

    def __str__(self):
        return f"{self.name}"

    # class Meta:
    #     db_table = "albums"
    #     verbose_name = "albums"
    #     verbose_name_plural = "albums"

webapp/forms.py
from django import forms
from django.forms import widgets

from webapp.models import Photo, Album


class PhotoForm(forms.ModelForm):
    class Meta:
        model = Photo
        fields = ['image', 'description', 'album', 'public']
        # widgets = {
        #     'album': widgets.RadioSelect
        # }


class AlbumForm(forms.ModelForm):
    class Meta:
        model = Album
        exclude = ['user']
        widgets = {
            'created_at': widgets.SelectDateWidget,
        }


class AlbumFormUser(forms.ModelForm):
    class Meta:
        model = Album
        exclude = ['user']


class UserForm(forms.ModelForm):
    class Meta:
        model = Album
        fields = ['user']
        widgets = {'user': widgets.CheckboxSelectMultiple}

webapp/views/album.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from webapp.forms import AlbumForm
from webapp.models import Album


# class AllAlbumsView(ListView):
#     template_name = 'albums/albums.html'
#     context_object_name = 'albums'
#
#     def get_queryset(self):
#         return Album.objects.all().order_by('-created_at')


class OneAlbumView(LoginRequiredMixin, DetailView):
    template_name = "albums/one_album.html"
    model = Album

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['photos'] = self.object.photos.order_by("-created_at")
        return context


class CreateAlbum(LoginRequiredMixin, CreateView):
    form_class = AlbumForm
    template_name = "albums/new.html"

    def get_success_url(self):
        return reverse('webapp:one_album', kwargs={"pk": self.object.pk})

    def form_valid(self, form):
        project = form.save()
        user_id = self.request.user
        project.user.add(user_id)
        project.save()
        return super().form_valid(form)


class UpdateAlbum(PermissionRequiredMixin, UpdateView):
    model = Album
    template_name = 'albums/update.html'
    form_class = AlbumForm
    context_object_name = 'album'
    permission_required = 'webapp.change_album'

    def get_success_url(self):
        return reverse('webapp:album_list')


class DeleteAlbum(PermissionRequiredMixin, DeleteView):
    model = Album
    context_object_name = 'album'
    template_name = 'albums/delete.html'
    success_url = reverse_lazy('webapp:index')
    permission_required = 'webapp.delete_album'

webapp/views/photos.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views import View
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from webapp.forms import PhotoForm
from webapp.models import Photo


# Create your views here.

class FavView(LoginRequiredMixin, View):
    def get(self, request, *args, pk, **kwargs):
        photo = Photo.objects.get(pk=pk)
        user = self.request.user
        if user in photo.fav.all():
            photo.fav.remove(user)
        else:
            photo.fav.add(user)
        return JsonResponse ({'count': photo.fav.count()})




class IndexView(ListView):  # пермишны на забудь
    template_name = 'photos/index.html'
    context_object_name = 'photos'

    def get_queryset(self):
        return Photo.objects.all().order_by('created_at')


class PhotoView(LoginRequiredMixin, DetailView):  # пермишны на забудь
    template_name = "photos/photo.html"
    model = Photo
    context_object_name = 'photo_obj'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class CreatePhoto(LoginRequiredMixin, CreateView):  # пермишны на забудь
    form_class = PhotoForm
    template_name = "photos/create.html"

    def get_success_url(self):
        return reverse('webapp:index')


class UpdatePhoto(PermissionRequiredMixin, UpdateView):  # пермишны на забудь
    model = Photo
    template_name = 'photos/update.html'
    form_class = PhotoForm
    context_object_name = 'photo'
    permission_required = 'webapp.change_photo'

    def get_success_url(self):
        return reverse('webapp:photo_view', kwargs={'pk': self.object.pk})


class DeletePhoto(PermissionRequiredMixin, DeleteView):  # пермишны на забудь
    model = Photo
    context_object_name = 'photo'
    template_name = 'photos/delete.html'
    success_url = reverse_lazy('webapp:index')
    permission_required = 'webapp.delete_photo'

webapp/templates/base.html
{% load static %}
{% load social_share %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible"
          content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
          crossorigin="anonymous">
    <link rel="stylesheet"
          href="{% static 'css/style.css' %}">
    <link rel="preconnect"
          href="https://fonts.googleapis.com">
    <link rel="preconnect"
          href="https://fonts.gstatic.com"
          crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
          rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Rubik"
          rel="stylesheet">
    <title>{% block title %}myapp{% endblock %}</title>
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark ">
    <div class="container ">
        <a class="navbar-brand"
           href="{% url "webapp:index" %}">Home</a>
        <button class="navbar-toggler"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarNav"
                aria-controls="navbarNav"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse "
             id="navbarNav">
            <ul class="navbar-nav mt-2 w-100 d-flex justify-content-evenly">
                {% block nav %}
                {% endblock %}
                {% if user.is_authenticated %}

                    {% block menu_links %}{% endblock %}
                    <li class="nav-item mt-2">
                        <p class="nav-link">Hello <a style="text-decoration: None"
                                                     href="{% url "accounts:profile" request.user.pk %}">{{ user.username }}</a>
                        </p>
                    </li>
                    <li class="menu-right mt-2"><a href="{% url 'accounts:logout' %}"
                                                   class="nav-link">Logout</a></li>
                {% else %}
                    <li class="menu-right"><a href="{% url 'accounts:login' %}?next={{ request.get_full_path }}"
                                              class="nav-link">Login</a></li>
                    <li class="nav-item mt-2">
                        <a class="nav-link "
                           href="{% url "accounts:registration" %}?next={{ request.get_full_path }}">Registration</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>

</nav>

<div class="container">
    {% block content %}
    {% endblock %}
</div>

</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
<script src="{% static 'js/index.js' %}"></script>
</html>